sudo: required

services:
  - docker

language: java
jdk: openjdk8

before_install: cp .maven.settings.xml "$HOME"/.m2/settings.xml

script: mvn verify cobertura:cobertura

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker push sdcplatform/actionexportersvc;
    fi
  - bash <(curl -s https://codecov.io/bash)

notifications:
  slack:
    rooms:
      secure: KRc+o003grFrMQpD73WoB4uQ6nyu/hFwUY3p2DyorEXd12Ms4c3adGYBIKrn/XoWYu40g7avvb+IKY8HzyT9Hm8+4wDOartk0a/gmO/ZvzLxCp63S/lWW4cX13kydgWE3tk7J6PrPP5Ps6UVLb4zVjXeeg3nalxKUCbHLfeyXW+vZFhANw5XiMDOSLuc9SEP3w/rsgBgwBfzpj0pM1fEJCQ0ZZoaAplvn0lFkdTiAyhtKGYHo/xSod7O4VwAfApUXUV8ABMwVFkaM3rGlIVDtoSZAH9eEwt3n9uPEr0jzJQovfVvV6oikaDVI2bX9iwnt9Cb38fCmN0iQtEyKl5P4syZy8zw19wA6GjEz7CS/xLIc8wHHIuBGqJZ5sTWQ+Ggzlbo2hd8geZaqpXiouHgqiABmtX1J6Dii9BYdZntXSMBFR+iCGFuueSeCrw5TBuH9EwoPRMAPYY20y/y51bAXKBzd3ScapJ/6edr4/qxhKX6Z/sFJcr54YZHOA/1czbdIKt5Ass2/kQxp2uzu/mmVeG+wjtxmM7iex2J0ldE+SkdlDodg99/byTOOy2kA4TmfXUyc6UI9H4dXJhsp1jA52q302O2M0dSMS8la7LZ6n4w3x4IvUMLyJgxohJykwHLTkwEWc0ERp6YBb1YlO3FUA8QWFvQ2F6couhx0SQhLA0=
    on_failure: always
    on_success: never

cache:
  directories:
  - $HOME/.m2

branches:
    only:
        - master