openapi: 3.0.1
info:
  title: Action Exporter Service
  description: API for actionexporter
  version: UNVERSIONED
servers:
  - url: localhost:8141/
tags:
  - info:
    description: Spring Boot Informational endpoints
  - export:
    description: Endpoint for triggering exports
paths:
  /health:
    get:
      summary: Returns health information about the service.
      description: Returns whether the service is up or not. An in-built Spring endpoint.
      security: []
      tags:
        - info
      responses:
        '200':
          description: A JSON indicating whether the service is up or not.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: UP
        '404':
          description: The service is incorrectly configured.
    /info:
      get:
        summary: Returns basic information about the service.
        description: Returns service information. An in-built Spring endpoint.
        security: []
        tags:
          - info
        responses:
          '200':
            description: A JSON of basic information about the service.
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    name:
                      type: string
                      example: actionsvc
                    version:
                      type: string
                      example: "10.42.0"
                    origin:
                      type: string
                      example: "git@github.com:ONSdigital/rm-actionexporter-service.git"
                    commit:
                      type: string
                      example: "06752afbf05f27c923ddf42d3cd2ec9eeafd3362"
                    branch:
                      type: string
                      example: master
                    built:
                      type: string
                      format: date-time
                      example: "2020-06-15T08:38:34Z"
          '404':
            description: The service is incorrectly configured.
  /export:
    get:
      summary: Triggers an export.
      description: Triggers an export of actions to a print file.
      responses:
        200:
          description: The export was successfully triggered.
        500:
          description: An unspecified exception was thrown. No export has been triggered and all transactions have been rolled back.