openapi: 3.0.1
info:
  title: Action Exporter Service
  description: API for actionexporter
  version: UNVERSIONED
servers:
  - url: localhost:8141/
tags:
  - info:
    description: Spring Boot Informational endpoints
  - name: template-endpoint
    description: Template Endpoint
  - name: template-mapping-endpoint
    description: Template Mapping Endpoint
paths:
  /health:
    get:
      summary: Returns health information about the service.
      description: Returns whether the service is up or not. An in-built Spring endpoint.
      security: []
      tags:
        - info
      responses:
        '200':
          description: A JSON indicating whether the service is up or not.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: UP
        '404':
          description: The service is incorrectly configured.
    /info:
      get:
        summary: Returns basic information about the service.
        description: Returns service information. An in-built Spring endpoint.
        security: []
        tags:
          - info
        responses:
          '200':
            description: A JSON of basic information about the service.
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    name:
                      type: string
                      example: actionsvc
                    version:
                      type: string
                      example: "10.42.0"
                    origin:
                      type: string
                      example: "git@github.com:ONSdigital/rm-actionexporter-service.git"
                    commit:
                      type: string
                      example: "06752afbf05f27c923ddf42d3cd2ec9eeafd3362"
                    branch:
                      type: string
                      example: master
                    built:
                      type: string
                      format: date-time
                      example: "2020-06-15T08:38:34Z"
          '404':
            description: The service is incorrectly configured.
  /templatemappings:
    get:
      tags:
        - template-mapping-endpoint
      summary: findAllTemplateMappings
      operationId: findAllTemplateMappingsUsingGET
      description: will return a list of all mappings for Action Exporter templates.
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TemplateMappingDTO'
        204:
          description: No content if no template mappings exist
          content: {}
        401:
          description: Unauthorized
          content: {}
        403:
          description: Forbidden
          content: {}
  /templatemappings/{actionType}:
    get:
      tags:
        - template-mapping-endpoint
      summary: findTemplateMapping
      operationId: findTemplateMappingUsingGET
      description: will return the details of the Action Exporter template mapping with the action type
      parameters:
        - name: actionType
          in: path
          description: the action type to map to the templates
          required: true
          schema:
            type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TemplateMappingDTO'
        401:
          description: Unauthorized
          content: {}
        403:
          description: Forbidden
          content: {}
        404:
          description: Not Found
          content: {}
    post:
      tags:
        - template-mapping-endpoint
      summary: storeTemplateMappings
      operationId: storeTemplateMappingsUsingPOST
      description:  will upload FreeMarker template mapping JSON to the Action Exporter template mapping with the specified action type.
      parameters:
        - name: actionType
          in: path
          description: the action type to map to the template
          required: true
          schema:
            type: string
      requestBody:
        description: templateMappingDTOList
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/TemplateMappingDTO'
        required: true
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TemplateMappingDTO'
        201:
          description: Created
          content: {}
        401:
          description: Unauthorized
          content: {}
        403:
          description: Forbidden
          content: {}
        404:
          description: Not Found
          content: {}
      x-codegen-request-body-name: templateMappingDTOList
  /templates:
    get:
      tags:
        - template-endpoint
      summary: findAllTemplates
      operationId: findAllTemplatesUsingGET
      description: will return a list of all Action Exporter templates
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TemplateExpressionDTO'
        204:
          description: If no templates are found
        401:
          description: Unauthorized
          content: {}

  /templates/{templateName}:
    get:
      tags:
        - template-endpoint
      summary: findTemplate
      operationId: findTemplateUsingGET
      description: will retutn a specific template
      parameters:
        - name: templateName
          in: path
          description: templateName
          required: true
          schema:
            type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TemplateExpressionDTO'
        401:
          description: Unauthorized
          content: {}
        404:
          description: If the template is not found
          content: {}
    post:
      tags:
        - template-endpoint
      summary: storeTemplate
      operationId: storeTemplateUsingPOST
      description: will upload a [FreeMarker](http://freemarker.org/) template to the Action Exporter
      parameters:
        - name: templateName
          in: path
          description: the name of the template
          required: true
          schema:
            type: string
      requestBody:
        content:
          multipart/form-data:
            schema:
              required:
                - file
              properties:
                file:
                  type: string
                  description: file
                  format: binary
        description: the contents of the freemarker template
        required: true
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TemplateExpressionDTO'
        201:
          description: Created
          content: {}
        401:
          description: Unauthorized
          content: {}
        403:
          description: Forbidden
          content: {}
components:
  schemas:
    TemplateExpressionDTO:
      type: object
      properties:
        content:
          type: string
          description: The actual template
          example: "<#list actionRequests as actionRequest>\n  ${(actionRequest.address.sampleUnitRef)!}|${actionRequest.iac?trim}|${(actionRequest.contact.forename?trim)!}|${(actionRequest.contact.emailaddress)!}\n  </#list>"
        dateModified:
          type: string
          format: date-time
          description: the date template was modified
          example: "2017-07-14T12:00:00Z"
        name:
          type: string
          description: the name of the freemarker template
          example: "initialPrint"
    TemplateMappingDTO:
      type: object
      properties:
        actionType:
          type: string
          description: the action type to use
        dateModified:
          type: string
          description: the data the template mapping was modified
          format: date-time
        fileNamePrefix:
          type: string
          description: the prefix for the file name
        template:
          type: string
          description: the name of freemarker template to use

