apiVersion: apps/v1
kind: Deployment
metadata:
  name: actionexportersvc
  labels:
    app: actionexportersvc
    env: dev
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: actionexportersvc
  template:
    metadata:
      labels:
        app: actionexportersvc
    spec:
      volumes:
        - name: sftp-data
          persistentVolumeClaim:
            claimName: sftp-pvc
      containers:
        - name: actionexportersvc
          image: "eu.gcr.io/{{ .Values.image.repository }}:{{.Values.image.tag }}"
          ports:
            - name: http-server
              containerPort: 8082
          volumeMounts:
            - name: sftp-data
              mountPath: "/home/demo/sftp"
          readinessProbe:
            httpGet:
              path: /info
              port: 8082
            initialDelaySeconds: 110
            periodSeconds: 20
            failureThreshold: 5
            successThreshold: 1
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /info
              port: 8082
            initialDelaySeconds: 120
            periodSeconds: 20
            failureThreshold: 5
            successThreshold: 1
            timeoutSeconds: 5
          env:
          - name: DB_HOST
            value: $(POSTGRES_SERVICE_HOST)
          - name: DB_PORT
            valueFrom:
              secretKeyRef:
                name: db-config
                key: db-port
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: db-config
                key: db-name
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: password
          - name: SECURITY_USER_NAME
            valueFrom:
              secretKeyRef:
                name: security-credentials
                key: security-user
          - name: SECURITY_USER_PASSWORD
            valueFrom:
              secretKeyRef:
                name: security-credentials
                key: security-password
          - name: RABBITMQ_USERNAME
            valueFrom:
              secretKeyRef:
                name: rabbitmq
                key: rabbitmq-username
          - name: RABBITMQ_PASSWORD
            valueFrom:
              secretKeyRef:
                name: rabbitmq
                key: rabbitmq-password
          - name: SERVER_PORT
            value: "8082"
          - name: SECURITY_BASIC_ENABLED
            value: "true"
          - name: SPRING_DATASOURCE_URL
            value: "jdbc:postgresql://$(DB_HOST):$(DB_PORT)/$(DB_NAME)?sslmode=disable"
          - name: LIQUIBASE_URL
            value: "jdbc:postgresql://$(DB_HOST):$(DB_PORT)/$(DB_NAME)"
          - name: RABBITMQ_HOST
            value: "$(RABBITMQ_SERVICE_HOST)"
          - name: RABBITMQ_PORT
            value: "5672"
          - name: SFTP_HOST
            value: "$(SFTP_SERVICE_HOST)"
          - name: SFTP_PORT
            value: "$(SFTP_SERVICE_PORT)"
          - name: SFTP_USERNAME
            value: "demo"
          - name: SFTP_PASSWORD
            value: "demo"
          - name: SFTP_DIRECTORY
            value: "/home/demo/sftp"
          - name: DATA_GRID_ADDRESS
            value: "$(REDIS_MASTER_SERVICE_HOST):$(REDIS_MASTER_SERVICE_PORT)"
          - name: FREEMARKER_DELAYFORNEWTEMPLATES
            value: "3600000"
          - name: DATA_GRID_LOCK_TIME_TO_LIVE_SECONDS
            value: "45"
          - name: LIQUIBASE_USER
            value: "$(DB_USERNAME)"
          - name: LIQUIBASE_PASSWORD
            value: "$(DB_PASSWORD)"
          - name: SPRING_DATASOURCE_USERNAME
            value: "$(DB_USERNAME)"
          - name: SPRING_DATASOURCE_PASSWORD
            value: "$(DB_PASSWORD)"
          - name: LOGGING_LEVEL_uk.gov.ons.ctp.response.action.export.scheduled
            value: "WARN"
          - name: EXPORT_SCHEDULE_CRON_EXPRESSION
            value: "*/30 * * * * *"
          - name: SPRING_ZIPKIN_ENABLED
            value: "true"
          - name: SPRING_ZIPKIN_BASEURL
            value: "http://$(ZIPKIN_SERVICE_HOST):$(ZIPKIN_SERVICE_PORT)/"
          resources:
            limits:
              cpu: 1000m
              memory: 2056Mi
            requests:
              cpu: 500m
              memory: 1028Mi
