env: minikube
namespace: minikube
loglevel: DEBUG

replicas: 1
rollingUpdate:
  maxSurge: 1
  maxUnavailable: 1

image:
  devRepo: eu.gcr.io/ons-rasrmbs-management
  name: eu.gcr.io/ons-rasrmbs-management
  tag: latest
  pullPolicy: Always

database:
  managedPostgres: false
  sqlProxyEnabled: false
  secrets:
    usernameKey: username
    passwordKey: password
    nameKey: db-name
  managedRedis: false

container:
  port: 8080
service:
  port: 8080

exportSchedule:
  cron: "*/30 * * * * *"

endpoints:
  enabled: true

resources:
  requests:
    memory: "256Mi"

sftp:
  directory: /home/demo/sftp
  test:
    enabled: true

managedRabbitMQ:
  enabled: false