//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2020.04.30 at 12:43:23 PM BST
//

package uk.gov.ons.ctp.response.action.message.instruction;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;

/**
 * Java class for ActionAddress complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="ActionAddress">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="estabType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="locality" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="organisationName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="category" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="line1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="line2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="townName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="postcode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="country" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ladCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="latitude" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="longitude" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "ActionAddress",
    propOrder = {
      "type",
      "estabType",
      "locality",
      "organisationName",
      "category",
      "line1",
      "line2",
      "townName",
      "postcode",
      "country",
      "ladCode",
      "latitude",
      "longitude"
    })
public class ActionAddress {

  protected String type;
  protected String estabType;
  protected String locality;
  protected String organisationName;
  protected String category;
  protected String line1;
  protected String line2;
  protected String townName;
  protected String postcode;
  protected String country;
  protected String ladCode;
  protected BigDecimal latitude;
  protected BigDecimal longitude;

  /**
   * Gets the value of the type property.
   *
   * @return possible object is {@link String }
   */
  public String getType() {
    return type;
  }

  /**
   * Sets the value of the type property.
   *
   * @param value allowed object is {@link String }
   */
  public void setType(String value) {
    this.type = value;
  }

  /**
   * Gets the value of the estabType property.
   *
   * @return possible object is {@link String }
   */
  public String getEstabType() {
    return estabType;
  }

  /**
   * Sets the value of the estabType property.
   *
   * @param value allowed object is {@link String }
   */
  public void setEstabType(String value) {
    this.estabType = value;
  }

  /**
   * Gets the value of the locality property.
   *
   * @return possible object is {@link String }
   */
  public String getLocality() {
    return locality;
  }

  /**
   * Sets the value of the locality property.
   *
   * @param value allowed object is {@link String }
   */
  public void setLocality(String value) {
    this.locality = value;
  }

  /**
   * Gets the value of the organisationName property.
   *
   * @return possible object is {@link String }
   */
  public String getOrganisationName() {
    return organisationName;
  }

  /**
   * Sets the value of the organisationName property.
   *
   * @param value allowed object is {@link String }
   */
  public void setOrganisationName(String value) {
    this.organisationName = value;
  }

  /**
   * Gets the value of the category property.
   *
   * @return possible object is {@link String }
   */
  public String getCategory() {
    return category;
  }

  /**
   * Sets the value of the category property.
   *
   * @param value allowed object is {@link String }
   */
  public void setCategory(String value) {
    this.category = value;
  }

  /**
   * Gets the value of the line1 property.
   *
   * @return possible object is {@link String }
   */
  public String getLine1() {
    return line1;
  }

  /**
   * Sets the value of the line1 property.
   *
   * @param value allowed object is {@link String }
   */
  public void setLine1(String value) {
    this.line1 = value;
  }

  /**
   * Gets the value of the line2 property.
   *
   * @return possible object is {@link String }
   */
  public String getLine2() {
    return line2;
  }

  /**
   * Sets the value of the line2 property.
   *
   * @param value allowed object is {@link String }
   */
  public void setLine2(String value) {
    this.line2 = value;
  }

  /**
   * Gets the value of the townName property.
   *
   * @return possible object is {@link String }
   */
  public String getTownName() {
    return townName;
  }

  /**
   * Sets the value of the townName property.
   *
   * @param value allowed object is {@link String }
   */
  public void setTownName(String value) {
    this.townName = value;
  }

  /**
   * Gets the value of the postcode property.
   *
   * @return possible object is {@link String }
   */
  public String getPostcode() {
    return postcode;
  }

  /**
   * Sets the value of the postcode property.
   *
   * @param value allowed object is {@link String }
   */
  public void setPostcode(String value) {
    this.postcode = value;
  }

  /**
   * Gets the value of the country property.
   *
   * @return possible object is {@link String }
   */
  public String getCountry() {
    return country;
  }

  /**
   * Sets the value of the country property.
   *
   * @param value allowed object is {@link String }
   */
  public void setCountry(String value) {
    this.country = value;
  }

  /**
   * Gets the value of the ladCode property.
   *
   * @return possible object is {@link String }
   */
  public String getLadCode() {
    return ladCode;
  }

  /**
   * Sets the value of the ladCode property.
   *
   * @param value allowed object is {@link String }
   */
  public void setLadCode(String value) {
    this.ladCode = value;
  }

  /**
   * Gets the value of the latitude property.
   *
   * @return possible object is {@link BigDecimal }
   */
  public BigDecimal getLatitude() {
    return latitude;
  }

  /**
   * Sets the value of the latitude property.
   *
   * @param value allowed object is {@link BigDecimal }
   */
  public void setLatitude(BigDecimal value) {
    this.latitude = value;
  }

  /**
   * Gets the value of the longitude property.
   *
   * @return possible object is {@link BigDecimal }
   */
  public BigDecimal getLongitude() {
    return longitude;
  }

  /**
   * Sets the value of the longitude property.
   *
   * @param value allowed object is {@link BigDecimal }
   */
  public void setLongitude(BigDecimal value) {
    this.longitude = value;
  }
}
