//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2020.04.30 at 12:43:23 PM BST
//

package uk.gov.ons.ctp.response.action.message.instruction;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

/**
 * Java class for ActionRequest complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="ActionRequest">
 *   &lt;complexContent>
 *     &lt;extension base="{http://ons.gov.uk/ctp/response/action/message/instruction}Action">
 *       &lt;sequence>
 *         &lt;element name="actionPlan" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="actionType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="questionSet" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="contact" type="{http://ons.gov.uk/ctp/response/action/message/instruction}ActionContact" minOccurs="0"/>
 *         &lt;element name="address" type="{http://ons.gov.uk/ctp/response/action/message/instruction}ActionAddress" minOccurs="0"/>
 *         &lt;element name="legalBasis" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="region" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="respondentStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="enrolmentStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="caseGroupStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="caseId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="priority" type="{http://ons.gov.uk/ctp/response/action/message/instruction}Priority" minOccurs="0"/>
 *         &lt;element name="caseRef" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="iac" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="events" type="{http://ons.gov.uk/ctp/response/action/message/instruction}ActionEvent"/>
 *         &lt;element name="exerciseRef" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="userDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="surveyName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="surveyRef" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="returnByDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="sampleUnitRef" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "ActionRequest",
    propOrder = {
      "actionPlan",
      "actionType",
      "questionSet",
      "contact",
      "address",
      "legalBasis",
      "region",
      "respondentStatus",
      "enrolmentStatus",
      "caseGroupStatus",
      "caseId",
      "priority",
      "caseRef",
      "iac",
      "events",
      "exerciseRef",
      "userDescription",
      "surveyName",
      "surveyRef",
      "returnByDate",
      "sampleUnitRef"
    })
public class ActionRequest extends Action {

  protected String actionPlan;

  @XmlElement(required = true)
  protected String actionType;

  protected String questionSet;
  protected ActionContact contact;
  protected ActionAddress address;
  protected String legalBasis;
  protected String region;
  protected String respondentStatus;
  protected String enrolmentStatus;
  protected String caseGroupStatus;
  protected String caseId;

  @XmlSchemaType(name = "string")
  protected Priority priority;

  protected String caseRef;
  protected String iac;

  @XmlElement(required = true)
  protected ActionEvent events;

  protected String exerciseRef;
  protected String userDescription;
  protected String surveyName;
  protected String surveyRef;
  protected String returnByDate;

  @XmlElement(required = true)
  protected String sampleUnitRef;

  /**
   * Gets the value of the actionPlan property.
   *
   * @return possible object is {@link String }
   */
  public String getActionPlan() {
    return actionPlan;
  }

  /**
   * Sets the value of the actionPlan property.
   *
   * @param value allowed object is {@link String }
   */
  public void setActionPlan(String value) {
    this.actionPlan = value;
  }

  /**
   * Gets the value of the actionType property.
   *
   * @return possible object is {@link String }
   */
  public String getActionType() {
    return actionType;
  }

  /**
   * Sets the value of the actionType property.
   *
   * @param value allowed object is {@link String }
   */
  public void setActionType(String value) {
    this.actionType = value;
  }

  /**
   * Gets the value of the questionSet property.
   *
   * @return possible object is {@link String }
   */
  public String getQuestionSet() {
    return questionSet;
  }

  /**
   * Sets the value of the questionSet property.
   *
   * @param value allowed object is {@link String }
   */
  public void setQuestionSet(String value) {
    this.questionSet = value;
  }

  /**
   * Gets the value of the contact property.
   *
   * @return possible object is {@link ActionContact }
   */
  public ActionContact getContact() {
    return contact;
  }

  /**
   * Sets the value of the contact property.
   *
   * @param value allowed object is {@link ActionContact }
   */
  public void setContact(ActionContact value) {
    this.contact = value;
  }

  /**
   * Gets the value of the address property.
   *
   * @return possible object is {@link ActionAddress }
   */
  public ActionAddress getAddress() {
    return address;
  }

  /**
   * Sets the value of the address property.
   *
   * @param value allowed object is {@link ActionAddress }
   */
  public void setAddress(ActionAddress value) {
    this.address = value;
  }

  /**
   * Gets the value of the legalBasis property.
   *
   * @return possible object is {@link String }
   */
  public String getLegalBasis() {
    return legalBasis;
  }

  /**
   * Sets the value of the legalBasis property.
   *
   * @param value allowed object is {@link String }
   */
  public void setLegalBasis(String value) {
    this.legalBasis = value;
  }

  /**
   * Gets the value of the region property.
   *
   * @return possible object is {@link String }
   */
  public String getRegion() {
    return region;
  }

  /**
   * Sets the value of the region property.
   *
   * @param value allowed object is {@link String }
   */
  public void setRegion(String value) {
    this.region = value;
  }

  /**
   * Gets the value of the respondentStatus property.
   *
   * @return possible object is {@link String }
   */
  public String getRespondentStatus() {
    return respondentStatus;
  }

  /**
   * Sets the value of the respondentStatus property.
   *
   * @param value allowed object is {@link String }
   */
  public void setRespondentStatus(String value) {
    this.respondentStatus = value;
  }

  /**
   * Gets the value of the enrolmentStatus property.
   *
   * @return possible object is {@link String }
   */
  public String getEnrolmentStatus() {
    return enrolmentStatus;
  }

  /**
   * Sets the value of the enrolmentStatus property.
   *
   * @param value allowed object is {@link String }
   */
  public void setEnrolmentStatus(String value) {
    this.enrolmentStatus = value;
  }

  /**
   * Gets the value of the caseGroupStatus property.
   *
   * @return possible object is {@link String }
   */
  public String getCaseGroupStatus() {
    return caseGroupStatus;
  }

  /**
   * Sets the value of the caseGroupStatus property.
   *
   * @param value allowed object is {@link String }
   */
  public void setCaseGroupStatus(String value) {
    this.caseGroupStatus = value;
  }

  /**
   * Gets the value of the caseId property.
   *
   * @return possible object is {@link String }
   */
  public String getCaseId() {
    return caseId;
  }

  /**
   * Sets the value of the caseId property.
   *
   * @param value allowed object is {@link String }
   */
  public void setCaseId(String value) {
    this.caseId = value;
  }

  /**
   * Gets the value of the priority property.
   *
   * @return possible object is {@link Priority }
   */
  public Priority getPriority() {
    return priority;
  }

  /**
   * Sets the value of the priority property.
   *
   * @param value allowed object is {@link Priority }
   */
  public void setPriority(Priority value) {
    this.priority = value;
  }

  /**
   * Gets the value of the caseRef property.
   *
   * @return possible object is {@link String }
   */
  public String getCaseRef() {
    return caseRef;
  }

  /**
   * Sets the value of the caseRef property.
   *
   * @param value allowed object is {@link String }
   */
  public void setCaseRef(String value) {
    this.caseRef = value;
  }

  /**
   * Gets the value of the iac property.
   *
   * @return possible object is {@link String }
   */
  public String getIac() {
    return iac;
  }

  /**
   * Sets the value of the iac property.
   *
   * @param value allowed object is {@link String }
   */
  public void setIac(String value) {
    this.iac = value;
  }

  /**
   * Gets the value of the events property.
   *
   * @return possible object is {@link ActionEvent }
   */
  public ActionEvent getEvents() {
    return events;
  }

  /**
   * Sets the value of the events property.
   *
   * @param value allowed object is {@link ActionEvent }
   */
  public void setEvents(ActionEvent value) {
    this.events = value;
  }

  /**
   * Gets the value of the exerciseRef property.
   *
   * @return possible object is {@link String }
   */
  public String getExerciseRef() {
    return exerciseRef;
  }

  /**
   * Sets the value of the exerciseRef property.
   *
   * @param value allowed object is {@link String }
   */
  public void setExerciseRef(String value) {
    this.exerciseRef = value;
  }

  /**
   * Gets the value of the userDescription property.
   *
   * @return possible object is {@link String }
   */
  public String getUserDescription() {
    return userDescription;
  }

  /**
   * Sets the value of the userDescription property.
   *
   * @param value allowed object is {@link String }
   */
  public void setUserDescription(String value) {
    this.userDescription = value;
  }

  /**
   * Gets the value of the surveyName property.
   *
   * @return possible object is {@link String }
   */
  public String getSurveyName() {
    return surveyName;
  }

  /**
   * Sets the value of the surveyName property.
   *
   * @param value allowed object is {@link String }
   */
  public void setSurveyName(String value) {
    this.surveyName = value;
  }

  /**
   * Gets the value of the surveyRef property.
   *
   * @return possible object is {@link String }
   */
  public String getSurveyRef() {
    return surveyRef;
  }

  /**
   * Sets the value of the surveyRef property.
   *
   * @param value allowed object is {@link String }
   */
  public void setSurveyRef(String value) {
    this.surveyRef = value;
  }

  /**
   * Gets the value of the returnByDate property.
   *
   * @return possible object is {@link String }
   */
  public String getReturnByDate() {
    return returnByDate;
  }

  /**
   * Sets the value of the returnByDate property.
   *
   * @param value allowed object is {@link String }
   */
  public void setReturnByDate(String value) {
    this.returnByDate = value;
  }

  /**
   * Gets the value of the sampleUnitRef property.
   *
   * @return possible object is {@link String }
   */
  public String getSampleUnitRef() {
    return sampleUnitRef;
  }

  /**
   * Sets the value of the sampleUnitRef property.
   *
   * @param value allowed object is {@link String }
   */
  public void setSampleUnitRef(String value) {
    this.sampleUnitRef = value;
  }
}
