//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2020.04.30 at 12:43:23 PM BST
//

package uk.gov.ons.ctp.response.action.message.instruction;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;

/**
 * Java class for ActionContact complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="ActionContact">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="forename" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="surname" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="phoneNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="emailAddress" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ruName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="tradingStyle" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "ActionContact",
    propOrder = {
      "title",
      "forename",
      "surname",
      "phoneNumber",
      "emailAddress",
      "ruName",
      "tradingStyle"
    })
public class ActionContact {

  protected String title;
  protected String forename;
  protected String surname;
  protected String phoneNumber;
  protected String emailAddress;
  protected String ruName;
  protected String tradingStyle;

  /**
   * Gets the value of the title property.
   *
   * @return possible object is {@link String }
   */
  public String getTitle() {
    return title;
  }

  /**
   * Sets the value of the title property.
   *
   * @param value allowed object is {@link String }
   */
  public void setTitle(String value) {
    this.title = value;
  }

  /**
   * Gets the value of the forename property.
   *
   * @return possible object is {@link String }
   */
  public String getForename() {
    return forename;
  }

  /**
   * Sets the value of the forename property.
   *
   * @param value allowed object is {@link String }
   */
  public void setForename(String value) {
    this.forename = value;
  }

  /**
   * Gets the value of the surname property.
   *
   * @return possible object is {@link String }
   */
  public String getSurname() {
    return surname;
  }

  /**
   * Sets the value of the surname property.
   *
   * @param value allowed object is {@link String }
   */
  public void setSurname(String value) {
    this.surname = value;
  }

  /**
   * Gets the value of the phoneNumber property.
   *
   * @return possible object is {@link String }
   */
  public String getPhoneNumber() {
    return phoneNumber;
  }

  /**
   * Sets the value of the phoneNumber property.
   *
   * @param value allowed object is {@link String }
   */
  public void setPhoneNumber(String value) {
    this.phoneNumber = value;
  }

  /**
   * Gets the value of the emailAddress property.
   *
   * @return possible object is {@link String }
   */
  public String getEmailAddress() {
    return emailAddress;
  }

  /**
   * Sets the value of the emailAddress property.
   *
   * @param value allowed object is {@link String }
   */
  public void setEmailAddress(String value) {
    this.emailAddress = value;
  }

  /**
   * Gets the value of the ruName property.
   *
   * @return possible object is {@link String }
   */
  public String getRuName() {
    return ruName;
  }

  /**
   * Sets the value of the ruName property.
   *
   * @param value allowed object is {@link String }
   */
  public void setRuName(String value) {
    this.ruName = value;
  }

  /**
   * Gets the value of the tradingStyle property.
   *
   * @return possible object is {@link String }
   */
  public String getTradingStyle() {
    return tradingStyle;
  }

  /**
   * Sets the value of the tradingStyle property.
   *
   * @param value allowed object is {@link String }
   */
  public void setTradingStyle(String value) {
    this.tradingStyle = value;
  }
}
