//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2020.04.30 at 12:43:23 PM BST
//

package uk.gov.ons.ctp.response.action.message.instruction;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

/**
 * Java class for ActionUpdate complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="ActionUpdate">
 *   &lt;complexContent>
 *     &lt;extension base="{http://ons.gov.uk/ctp/response/action/message/instruction}Action">
 *       &lt;sequence>
 *         &lt;element name="priority" type="{http://ons.gov.uk/ctp/response/action/message/instruction}Priority"/>
 *         &lt;element name="events" type="{http://ons.gov.uk/ctp/response/action/message/instruction}ActionEvent"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "ActionUpdate",
    propOrder = {"priority", "events"})
public class ActionUpdate extends Action {

  @XmlElement(required = true)
  @XmlSchemaType(name = "string")
  protected Priority priority;

  @XmlElement(required = true)
  protected ActionEvent events;

  /**
   * Gets the value of the priority property.
   *
   * @return possible object is {@link Priority }
   */
  public Priority getPriority() {
    return priority;
  }

  /**
   * Sets the value of the priority property.
   *
   * @param value allowed object is {@link Priority }
   */
  public void setPriority(Priority value) {
    this.priority = value;
  }

  /**
   * Gets the value of the events property.
   *
   * @return possible object is {@link ActionEvent }
   */
  public ActionEvent getEvents() {
    return events;
  }

  /**
   * Sets the value of the events property.
   *
   * @param value allowed object is {@link ActionEvent }
   */
  public void setEvents(ActionEvent value) {
    this.events = value;
  }
}
