//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2020.04.30 at 12:43:23 PM BST
//

package uk.gov.ons.ctp.response.action.message.instruction;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;

/**
 * Java class for Action complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="Action">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="actionId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="responseRequired" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "Action",
    propOrder = {"actionId", "responseRequired"})
@XmlSeeAlso({ActionCancel.class, ActionRequest.class, ActionUpdate.class})
public class Action {

  @XmlElement(required = true)
  protected String actionId;

  protected boolean responseRequired;

  /**
   * Gets the value of the actionId property.
   *
   * @return possible object is {@link String }
   */
  public String getActionId() {
    return actionId;
  }

  /**
   * Sets the value of the actionId property.
   *
   * @param value allowed object is {@link String }
   */
  public void setActionId(String value) {
    this.actionId = value;
  }

  /** Gets the value of the responseRequired property. */
  public boolean isResponseRequired() {
    return responseRequired;
  }

  /** Sets the value of the responseRequired property. */
  public void setResponseRequired(boolean value) {
    this.responseRequired = value;
  }
}
