//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2020.04.30 at 12:43:23 PM BST
//

package uk.gov.ons.ctp.response.action.message.instruction;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each Java content interface and Java element interface
 * generated in the uk.gov.ons.ctp.response.action.message.instruction package.
 *
 * <p>An ObjectFactory allows you to programatically construct new instances of the Java
 * representation for XML content. The Java representation of XML content can consist of schema
 * derived interfaces and classes representing the binding of schema type definitions, element
 * declarations and model groups. Factory methods for each of these are provided in this class.
 */
@XmlRegistry
public class ObjectFactory {

  private static final QName _ActionInstruction_QNAME =
      new QName("http://ons.gov.uk/ctp/response/action/message/instruction", "actionInstruction");

  /**
   * Create a new ObjectFactory that can be used to create new instances of schema derived classes
   * for package: uk.gov.ons.ctp.response.action.message.instruction
   */
  public ObjectFactory() {}

  /** Create an instance of {@link ActionInstruction } */
  public ActionInstruction createActionInstruction() {
    return new ActionInstruction();
  }

  /** Create an instance of {@link JAXBElement }{@code <}{@link ActionInstruction }{@code >}} */
  @XmlElementDecl(
      namespace = "http://ons.gov.uk/ctp/response/action/message/instruction",
      name = "actionInstruction")
  public JAXBElement<ActionInstruction> createActionInstruction(ActionInstruction value) {
    return new JAXBElement<ActionInstruction>(
        _ActionInstruction_QNAME, ActionInstruction.class, null, value);
  }

  /** Create an instance of {@link Action } */
  public Action createAction() {
    return new Action();
  }

  /** Create an instance of {@link ActionCancel } */
  public ActionCancel createActionCancel() {
    return new ActionCancel();
  }

  /** Create an instance of {@link ActionRequest } */
  public ActionRequest createActionRequest() {
    return new ActionRequest();
  }

  /** Create an instance of {@link ActionEvent } */
  public ActionEvent createActionEvent() {
    return new ActionEvent();
  }

  /** Create an instance of {@link ActionUpdate } */
  public ActionUpdate createActionUpdate() {
    return new ActionUpdate();
  }

  /** Create an instance of {@link ActionAddress } */
  public ActionAddress createActionAddress() {
    return new ActionAddress();
  }

  /** Create an instance of {@link ActionContact } */
  public ActionContact createActionContact() {
    return new ActionContact();
  }
}
