//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2020.04.30 at 12:43:23 PM BST
//

package uk.gov.ons.ctp.response.action.message.instruction;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

/**
 * Java class for Priority.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <p>
 *
 * <pre>
 * &lt;simpleType name="Priority">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="highest"/>
 *     &lt;enumeration value="higher"/>
 *     &lt;enumeration value="medium"/>
 *     &lt;enumeration value="lower"/>
 *     &lt;enumeration value="lowest"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 */
@XmlType(name = "Priority")
@XmlEnum
public enum Priority {
  @XmlEnumValue("highest")
  HIGHEST("highest"),
  @XmlEnumValue("higher")
  HIGHER("higher"),
  @XmlEnumValue("medium")
  MEDIUM("medium"),
  @XmlEnumValue("lower")
  LOWER("lower"),
  @XmlEnumValue("lowest")
  LOWEST("lowest");
  private final String value;

  Priority(String v) {
    value = v;
  }

  public String value() {
    return value;
  }

  public static Priority fromValue(String v) {
    for (Priority c : Priority.values()) {
      if (c.value.equals(v)) {
        return c;
      }
    }
    throw new IllegalArgumentException(v);
  }
}
