//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2020.04.30 at 03:22:37 PM BST
//

package uk.gov.ons.ctp.response.action.message.feedback;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;

/**
 * Java class for Outcome.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <p>
 *
 * <pre>
 * &lt;simpleType name="Outcome">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="REQUEST_FAILED"/>
 *     &lt;enumeration value="REQUEST_ACCEPTED"/>
 *     &lt;enumeration value="REQUEST_COMPLETED"/>
 *     &lt;enumeration value="REQUEST_DECLINED"/>
 *     &lt;enumeration value="REQUEST_COMPLETED_DEACTIVATE"/>
 *     &lt;enumeration value="REQUEST_COMPLETED_DISABLE"/>
 *     &lt;enumeration value="CANCELLATION_FAILED"/>
 *     &lt;enumeration value="CANCELLATION_ACCEPTED"/>
 *     &lt;enumeration value="CANCELLATION_COMPLETED"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 */
@XmlType(name = "Outcome")
@XmlEnum
public enum Outcome {
  REQUEST_FAILED,
  REQUEST_ACCEPTED,
  REQUEST_COMPLETED,
  REQUEST_DECLINED,
  REQUEST_COMPLETED_DEACTIVATE,
  REQUEST_COMPLETED_DISABLE,
  CANCELLATION_FAILED,
  CANCELLATION_ACCEPTED,
  CANCELLATION_COMPLETED;

  public String value() {
    return name();
  }

  public static Outcome fromValue(String v) {
    return valueOf(v);
  }
}
