//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2020.04.30 at 03:22:37 PM BST
//

@javax.xml.bind.annotation.XmlSchema(
    namespace = "http://ons.gov.uk/ctp/response/action/message/feedback")
package uk.gov.ons.ctp.response.action.message.feedback;
